# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: ai-chatbot-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_chatbot
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
